// flow-typed signature: aee47a618ce340866d26a7aef0423636
// flow-typed version: <<STUB>>/fuzzysort_v^1.0.5/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fuzzysort'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fuzzysort' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fuzzysort/fuzzysort' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fuzzysort/fuzzysort.js' {
  declare module.exports: $Exports<'fuzzysort/fuzzysort'>;
}
