// flow-typed signature: 11a7fd9863ca710d7e377a3fd696b004
// flow-typed version: <<STUB>>/rollup-plugin-sizes_v^0.4.2/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-sizes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-sizes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-sizes/test/specimens/entry' {
  declare module.exports: any;
}

declare module 'rollup-plugin-sizes/test/specimens/maths' {
  declare module.exports: any;
}

declare module 'rollup-plugin-sizes/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-sizes/index' {
  declare module.exports: $Exports<'rollup-plugin-sizes'>;
}
declare module 'rollup-plugin-sizes/index.js' {
  declare module.exports: $Exports<'rollup-plugin-sizes'>;
}
declare module 'rollup-plugin-sizes/test/specimens/entry.js' {
  declare module.exports: $Exports<'rollup-plugin-sizes/test/specimens/entry'>;
}
declare module 'rollup-plugin-sizes/test/specimens/maths.js' {
  declare module.exports: $Exports<'rollup-plugin-sizes/test/specimens/maths'>;
}
declare module 'rollup-plugin-sizes/test/test.js' {
  declare module.exports: $Exports<'rollup-plugin-sizes/test/test'>;
}
